"""is_active is added to the models

Revision ID: 2e4017fb4e9a
Revises: 
Create Date: 2024-10-23 22:07:14.412304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e4017fb4e9a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_teams_city', table_name='teams')
    op.drop_index('ix_teams_country', table_name='teams')
    op.drop_index('ix_teams_name', table_name='teams')
    op.drop_table('teams')
    op.drop_index('ix_players_firstname', table_name='players')
    op.drop_index('ix_players_lastname', table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('firstname', sa.VARCHAR(length=30), nullable=False),
    sa.Column('lastname', sa.VARCHAR(length=30), nullable=False),
    sa.Column('birthdate', sa.DATE(), nullable=False),
    sa.Column('height', sa.FLOAT(), nullable=False),
    sa.Column('nationality', sa.VARCHAR(length=30), nullable=False),
    sa.Column('position', sa.VARCHAR(length=20), nullable=False),
    sa.Column('dorsal', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('team_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_players_lastname', 'players', ['lastname'], unique=False)
    op.create_index('ix_players_firstname', 'players', ['firstname'], unique=False)
    op.create_table('teams',
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('country', sa.VARCHAR(length=20), nullable=False),
    sa.Column('city', sa.VARCHAR(length=20), nullable=False),
    sa.Column('stadium', sa.VARCHAR(length=20), nullable=False),
    sa.Column('color', sa.VARCHAR(length=20), nullable=False),
    sa.Column('coach', sa.VARCHAR(length=30), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_teams_name', 'teams', ['name'], unique=False)
    op.create_index('ix_teams_country', 'teams', ['country'], unique=False)
    op.create_index('ix_teams_city', 'teams', ['city'], unique=False)
    # ### end Alembic commands ###
