name: Football API CI/CD

on:
  push:
    branches:
      - main
      - dev

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Execute migrations
        run: 'alembic -x db_url=sqlite:///./database.db: upgrade head'

      - name: Run tests
        run: pytest
