name: Football API CI/CD

on:
  push:
    branches:
      - main
      - dev

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Run tests
        run: pytest
